# -*- coding: utf-8 -*-
"""PredictOutput.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153pFa9kVq5vbESlvqoUzqQVrsRZRJDwE
"""

import cv2
import os
import pickle
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
import glob
import matplotlib.pyplot as plt
from PIL import Image
from skimage.io import imread
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support

sour_dir = input("Please input your testing folder: ")

sour_dir = os.path.abspath(sour_dir)

with open('./model_rf1.pkl','rb') as fr:
	model_v1 = pickle.load(fr)
model = model_v1['model']

class_dict ={
    '20x26':0,
    '20x28':1,
    '28x22':2,
    '35x19':3,
    '35x22':4,
    '35x28':5,
    '35x30':6,
    '42x22':7,
    '42x30':8
}
new_dict = {v : k for k, v in class_dict.items()}

file_name_list =[]
class_list= []
count = 0
for root, dirs, files in os.walk(f'{sour_dir}'):
  for file in files:
    count+=1
    img_path = os.path.join(root,file)
    img = cv2.imread(img_path,cv2.IMREAD_GRAYSCALE)
    output = cv2.Sobel(img,-1,1,3,3,7)
    img = output.flatten()
    pred = model.predict(img.reshape(-1,1228800))[0]
    pred = new_dict[pred]
    file_name_list.append(file)
    class_list.append(pred)
    print(f'================{count}================')
    print(f'file_name: {file}','---->', f'Class: {pred}')
    print('=====================================')
df = pd.DataFrame({    
    'class':class_list,
    'filename':file_name_list
})

print(df.sort_values(by=['class']))

exit = input('Please Press Any to Exit')