# -*- coding: utf-8 -*-
"""ImageExtract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14oro9onxAWnJ1xTtN5ESyypalbB6kZRM
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import cv2
import pandas as pd
import os
from shutil import copy
import glob
import matplotlib.pyplot as plt

goal_dir = r'/content/drive/MyDrive/Neocis_Ass/Input_Video'

train_dir = r'/content/drive/MyDrive/Neocis_Ass/Image_fromVideo'

# Capture the video and seperate into different image
def video_img(video, save_path):
    cap = cv2.VideoCapture(video)
    while cap.isOpened():
        exis, image = cap.read()
        if exis:
            num = len(os.listdir(save_path))
            cv2.imwrite(os.path.join(save_path, f'{num+1}.png'), image)
        else:
            break
    cv2.destroyAllWindows()
    cap.release()

# Seperate the video into image by drill size
for name in glob.glob(r'/content/drive/MyDrive/Neocis_Ass/Image_Video/*'):
  class_name = os.path.split(name)[-1][0:5]
  save_path = (os.path.join(train_dir,class_name))
  os.makedirs(save_path, exist_ok = True)
  os.chdir(save_path)
  video_img(name,save_path)

img = cv2.imread(r'/content/drive/MyDrive/Neocis_Ass/Image_fromVideo/20x26/40.png',cv2.IMREAD_GRAYSCALE)

plt.imshow(img,cmap ='gray')
plt.colorbar()

# Transfer into gray scale and do class balance
gray_dir = r'/content/drive/MyDrive/Neocis_Ass/Image_gray'
for name in glob.glob(r'/content/drive/MyDrive/Neocis_Ass/Image_fromVideo/*'):
  print(name)
  count =0
  for root, dirs, files in os.walk(name):
    for file in files:
      count+=1
      if count == 2:
        save_dir = os.path.split(root)[-1]
        goal_dir = os.path.join(gray_dir,save_dir)
        # print(goal_dir)
        os.makedirs(goal_dir,exist_ok = True)
        final_img_path = os.path.join(root,file)
        img = cv2.imread(f'{final_img_path}',cv2.IMREAD_GRAYSCALE)
        os.chdir(goal_dir)
        cv2.imwrite(f'{file}',img)
        count = 0
    print(goal_dir)
    print('=====================')
