# -*- coding: utf-8 -*-
"""SOBEL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uV1kXocWdpHq7GGY5xfpCKi4AezirOFG
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import cv2
import pandas as pd
import os
from shutil import copy
import glob
import matplotlib.pyplot as plt
from skimage import feature as ft

df = pd.DataFrame(np.array([[np.array([1,2]),2,3],[np.array([3,25]),3,5],[np.array([13,22]),7,8]]))

np.vstack(df[0])

# img = cv2.imread(r'/content/drive/MyDrive/Neocis_Ass/Image_HOG/20x26/10.png', cv2.IMREAD_GRAYSCALE)
# # features = ft.hog(img,orientations=6,pixels_per_cell=[20,20],cells_per_block=[2,2],visualize=True)
# plt.imshow(img,cmap=plt.cm.gray)
# plt.show()
# print(img.shape)

img = cv2.imread(r'/content/drive/MyDrive/Neocis_Ass/Image_gray/20x26/1008.png',cv2.IMREAD_GRAYSCALE)

output = cv2.Sobel(img,-1,1,3,3,7)

plt.imshow(output)

# Transfer into gray scale and do class balance
hog_dir = r'/content/drive/MyDrive/Neocis_Ass/Img_SOBEL'
for name in glob.glob(r'/content/drive/MyDrive/Neocis_Ass/Image_fromVideo/*'):
  print(name)
  count =0
  for root, dirs, files in os.walk(name):
    for file in files:
      count+=1
      if count == 6:
        save_dir = os.path.split(root)[-1]
        goal_dir = os.path.join(hog_dir,save_dir)
        # print(goal_dir)
        os.makedirs(goal_dir,exist_ok = True)
        final_img_path = os.path.join(root,file)
        img = cv2.imread(f'{final_img_path}',cv2.IMREAD_GRAYSCALE)
        output = cv2.Sobel(img,-1,1,3,3,7)
        sav_img = output
        os.chdir(goal_dir)
        cv2.imwrite(f'{file}',sav_img)
        count = 0
    print(goal_dir)
    print('=====================')